name: check
on:
  pull_request:
    branches:
      - main

env:
  PYTHONUNBUFFERED: 1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v2

      - uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v2
        with:
          activate-environment: cf
          environment-file: environment.yml
          auto-activate-base: true
          miniforge-version: latest
          miniforge-variant: Mambaforge

      - name: Check request YAML files
        shell: bash -el {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda activate cf
          python -m conda_forge_admin_requests check
