name: check
on:
  pull_request:
    branches:
      - main

env:
  PYTHONUNBUFFERED: 1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3.0.4
        with:
          activate-environment: cf
          environment-file: environment.yml
          auto-activate-base: true
          miniforge-version: latest

      - name: Check request YAML files
        shell: bash -el {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda activate cf
          python -m conda_forge_admin_requests check
